# Generated by Django 6.0.7 on 2026-07-12 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('color', models.CharField(choices=[('#fff9a8', 'Yellow'), ('#a8e6cf', 'Green'), ('#ffb3b3', 'Pink'), ('#b3d9ff', 'Blue'), ('#d9b3ff', 'Purple')], default='#fff9a8', max_length=7)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
